### ISSUE TITLE
unknown locale: UTF-8 in preprocessing.py file

### ISSUE THREAD

**Issue by ghost** [pielstroem/Topics#1]
Hi,

I'm trying to execute the jupiter notebook **Introduction**. However I've been having an issue with the line "from dariah_topics import preprocessing as pre". I get always the following error: 

Traceback (most recent call last):

File "/Users/MissOgra/Topics/dariah_topics/preprocessing.py", line 28, in <module>
    import regex
File "/Users/MissOgra/anaconda3/lib/python3.5/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
File "/Users/MissOgra/anaconda3/lib/python3.5/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
File "/Users/MissOgra/anaconda3/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
File "/Users/MissOgra/anaconda3/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Any ideas about how can I resolve this problem? 

Thank you.

Carolina

**Comment by SinaB0ck** [comment]
Hi Carolina,

if you using Anaconda on Mac OS X one this solution might help -> http://patrick.arminio.info/fix-valueerror-unknown-locale-utf8/
